blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path ('', views.article_list_view, name='article_list'), 
    path ('detail/<slug>', views.ArticleDetail.as_view(), name='article_detail'),
    # path ('search/', views.search_view, name='search'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details_view, name='cart_details'),
    path('add/', views.add_product_to_cart_view, name='add_product_to_cart'),
    path('remove/', views.remove_from_cart_view, name='remove_from_cart'),
    path('clear/', views.clear_cart_view, name='clear_cart'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    # Django Admin Urls
    path('admin/', admin.site.urls),

    # # Django Tool-Bar Urls
    # path("__debug__/", include("debug_toolbar.urls")),

    # Product App Urls
    path('products/', include('product.urls', namespace='product')),

    # Blog App Urls
    path('blog/', include('blog.urls', namespace='blog')),

    # Cart App Urls
    path('cart/', include('cart.urls', namespace='cart')),

    # Pages App Urls
    path('', include('pages.urls', namespace='pages')),

    # Django Ckeditor-5 Urls
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),

]

# serve static and media files from development server
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.product_list_view, name='product_list'),
    path("detail/<slug:slug>/", views.product_detail_view, name="product_detail"),
    path("search/", views.search_view, name="search"),
    path('download-pdf/<int:product_id>/', views.download_pdf_view, name='download_pdf'),
]

product/models.py
from django.db import models
from django.urls import reverse

from taggit.managers import TaggableManager


class BaseModel(models.Model):
    datetime_created = models.DateTimeField(auto_now_add=True)
    
    datetime_updated = models.DateTimeField(auto_now=True)
    
    is_active = models.BooleanField(default=True)


class Content(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='product_contents')
    
    name = models.CharField(max_length=255, blank=True, null=True)
    
    content = models.TextField()


class Brand(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Industry(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Industry'
        verbose_name_plural = 'Industries'


class Application(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Type(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Product(BaseModel):
    name = models.CharField(max_length=255, unique=True)
    
    slug = models.SlugField(max_length=255, unique=True)
    
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, null=True, blank=True, related_name='products')
    
    industry = models.ForeignKey(Industry, on_delete=models.PROTECT, null=True, blank=True, related_name='products')
    
    description = models.TextField(blank=True, null=True)
    
    technical_information = models.TextField(null=True, blank=True)
    
    application = models.ForeignKey(Application, on_delete=models.PROTECT, related_name='products')
    # application = models.ManyToManyField(Application, related_name='products')
    
    type = models.ForeignKey(Type, on_delete=models.PROTECT, related_name='products')
    # type = models.ManyToManyField(Type, related_name='products')
    
    image = models.ImageField(upload_to='images/products/')
    
    product_pdf = models.FileField(upload_to='products/product_pdf/', blank=True, null=True)
    
    similar_tags = TaggableManager(blank=True)

    def __str__(self):
        return f'id: {self.id} | name: {self.name}'

    def get_absolute_url(self):
        return reverse("product:product_detail", kwargs={"slug": self.slug})


class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name="product_images")
    
    content = models.TextField(null=True, blank=True)
    
    image = models.ImageField(upload_to="images/")
    
    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'ProductImage'
        verbose_name_plural = 'ProductImages'

product/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(max_length=250)

product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.http import FileResponse
from django.contrib import messages
from django.core.paginator import Paginator
from urllib.parse import urlencode

from .models import Product, Brand, Industry, ProductImages
from .forms import SearchForm
from .filters import ProductFilter


def product_list_view(request):
    products = Product.objects.filter(is_active=True)
    
    form = SearchForm()
    
    if 'search' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            data = form.cleaned_data['search']
            if data.isdigit():
                messages.error(request, 'It must be character a-z, A-Z', 'danger')
                return render(request, 'product/product_list.html', {"products": products})
            else:
                products = Product.objects.filter(Q(name__icontains=data))
    
    f = ProductFilter(request.GET, queryset=products)
    
    products = f.qs
    
    paginator = Paginator(products, 3)
    
    page_number = request.GET.get('page')
    
    url_data = request.GET.copy()
    
    if 'page' in url_data:
        del url_data['page']
    
    page_obj = paginator.get_page(page_number)
    
    # for field in f.form:
    #     print(field)
    
    context = {
        'products' : page_obj,
        'page_number' : page_number,
        'filter':f,
        'url_data': urlencode(url_data),
        'form':form,
    }
    
    return render(request, 'product/product_list.html', context)


def product_detail_view(request, slug):
    product = get_object_or_404(
        Product.objects.select_related('type', 'application').prefetch_related('product_contents'),
        slug= slug
    )
    
    product_images = ProductImages.objects.filter(product__slug = slug)
    
    similar_products = product.similar_tags.similar_objects()[:5]
    
    
    if product.type.name == 'Product':
        
        products = Product.objects.select_related('type', 'application').filter(type=1)[:5]
        
        context = {
            'product': product,
            'product_images': product_images,
            'similar_products': similar_products,
            'products': products,
        }
        
        return render(request, 'product/product_detail.html', context)
    
    elif product.type.name == 'Solution':
        solutions = Product.objects.select_related('type', 'application').filter(type=2)[:5]
        
        context = {
            'product': product,
            'product_images': product_images,
            'similar_products': similar_products,
            'solutions': solutions,
        }
        
        return render(request, 'product/solution_detail.html', context)
    
    services = Product.objects.select_related('type', 'application').filter(type=3)[:5]
    
    context = {
        'product': product,
        'product_images': product_images,
        'similar_products': similar_products,
        'services': services,
    }
    
    return render(request, 'product/service_detail.html', context)


def download_pdf_view(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if product.product_pdf:
        return FileResponse(product.product_pdf, as_attachment=True)


def search_view(request):
    search = SearchForm(request.POST)
    if search.is_valid():
        data = search.cleaned_data['search']
        if data.isdigit():
            messages.error(request, 'It must be character a-z, A-Z', 'danger')
            return render(request, 'product/product_list.html', {"products": products})
        else:
            products = Product.objects.filter(Q(name__icontains=data))

            f = ProductFilter(request.GET, queryset=products)

            products = f.qs
            
            paginator = Paginator(products, 3)
            
            page_number = request.GET.get('page')
            
            url_data = request.GET.copy()
            
            if 'page' in url_data:
                del url_data['page']
            
            page_obj = paginator.get_page(page_number)
            
            context = {
                'products' : page_obj,
                'page_number' : page_number,
                'filter':f,
                'url_data': urlencode(url_data)
            }
            
            return render(request, 'product/product_list.html', context)
    else:
        return redirect('product:product_list' )

product/templates/product/product_detail.html
{% extends "_base.html" %}

{% load static %}

{% block title %}

    Product Detail

{% endblock title %}

{% block body %}

    
    <!-- 
    ========================
    page title 
    =========================== 
    -->
    <section class="page-title page-title-layout7 bg-overlay bg-parallax text-center">
        <div class="bg-img"><img src="{{ product.image.url }}" alt="background"></div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-6 offset-xl-3" style='padding-top:150px;padding-bottom:150px;'>
                    <h1 class="pagetitle__heading mb-0">{{ product.name }}</h1>
                </div><!-- /.col-xl-6 -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section><!-- /.page-title -->

    <!-- ======================
    Text Content Section
    ========================= -->
    <section class="text-content-section pb-90">
    <div class="container">
        <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <aside class="sidebar mb-30">
            <div class="widget widget-categories">
                <h5 class="widget__title">products</h5>
                <div class="widget-content">
                <ul class="list-unstyled">
                    {% for relate_product in products %}
                        <li><a href="{{ relate_product.get_absolute_url }}" {% if relate_product.id == product.id %}class="active" {% endif %}>{{ relate_product.name }}</a></li>
                    {% endfor %}
                </ul>
                </div><!-- /.widget-content -->
            </div><!-- /.widget-categories -->
            <div class="widget widget-contact bg-secondary">
                <form method="post" action="{% url 'cart:add_product_to_cart' %}">
                    {% csrf_token %}
                    <div class="widget-body">
                        <input name='product_id' style="display:none;" class="btn btn__primary btn__block" value="{{ product.id }}" >
                        <button type="submit" class="btn btn__primary btn__block">Add To Cart</button>
                    </div><!-- /.widget-content -->
                </form>
            </div><!-- /.widget-contact -->
            <div class="widget widget-download">
                <h5 class="widget__title">User Manual</h5>
                <div class="widget-body">
                <a href="{% url 'product:download_pdf' product.id %}" class="btn btn__secondary btn__block mb-20">
                    <span>Download</span>
                    <img src="{% static "product/assets/images/icons/pdf.png"%}" alt="pdf">
                </a>
                </div><!-- /.widget-content -->
            </div><!-- /.widget-download -->
            </aside><!-- /.sidebar -->
        </div><!-- /.col-lg-4 -->
        <div class="col-sm-12 col-md-12 col-lg-8">
            {% comment %} 
                <h5 class="mb-40 font-italic">A leading developer of A grade commercial, industrial and residential
                projects in USA.
                Since foundation we doubled turnover year on year, with its staff numbers swelling accordingly.</h5>
            {% endcomment %}
            <!-- ======================
            portfolio-gallery
            ========================= -->
            <section class="portfolio-gallery py-0">
                <div class="container">
                    <div class="row">
                        <!-- portfolio item -->
                        {% for product_image in product_images %}
                            <div class="col-sm-6 col-md-6 col-lg-4">
                                <div class="portfolio-item">
                                    <div class="portfolio-item__img">
                                    <a class="popup-gallery-item" href="{{ product_image.image.url }}">
                                        <img src="{{ product_image.image.url }}" alt="portfolio img">
                                    </a>
                                    </div><!-- /.portfolio-img -->
                                </div><!-- /.portfolio-item -->
                            </div><!-- /.col-lg-4 -->
                        {% endfor %}
                    </div><!-- /.row -->
                </div><!-- /.container -->
            </section>
            <!-- /.portfolio gallery -->
            
            <div class="text__block mb-30">
            <h5 class="text__block-title">Overview</h5>
            <p class="text__block-desc">
                {{ product.description|linebreaks }}
            </p>
            </div><!-- /.text-block -->
            <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="features-list mb-30">
                <div class="row">
                    {% for content in product.product_contents.all %}    
                        <div class="col-sm-12 col-md-12 col-lg-6">
                            <div class="feature-list-item">
                                <div class="feature-item__content">
                                <h4 class="feature-item__title">{{ content.name }}</h4>
                                <p class="feature-item__desc">
                                    {{ content.content|linebreaksbr }}
                                </p>
                                </div><!-- /.feature-content -->
                            </div><!-- /.feature-item -->
                        </div><!-- /.col-lg-6 -->
                    {% endfor %}
                </div><!-- /.row -->
                </div><!-- /.features-list -->
            </div><!-- /.col-lg-12 -->
            </div>

            {% comment %} 
                <div class="text__block">
                    <h5 class="text__block-title">How It Works?!</h5>
                    <p class="text__block-desc">We have more than twenty years of experience. During that time, we’ve become
                    expert in freight transportation by air and all its related products. We work closely with all major
                    airlines around the world. Ongoing negotiations ensure that we always have the cargo space we need and
                    offer you competitive rates.</p>
                </div><!-- /.text-block -->

                <div class="video-banner mb-50">
                    <img src="assets/images/banners/3.jpg" alt="banner">
                    <a class="video__btn video__btn-white popup-video" href="https://www.youtube.com/watch?v=nrJtHemSPW4">
                        <div class="video__player">
                        <span class="video__player-animation"></span>
                        <span class="video__player-animation video__player-animation-2"></span>
                        <i class="fa fa-play"></i>
                        </div>
                        <span class="video__btn-title color-white">Watch Video!</span>
                    </a>
                </div><!-- /.video -->

                <h5 class="fz-25 mt-20">Key Benifits</h5>
                <div id="accordion">
                <div class="accordion-item">
                    <div class="accordion-item__header" data-toggle="collapse" data-target="#collapse1">
                    <a class="accordion-item__title" href="#">Which Plan Is Right For Me?</a>
                    </div><!-- /.accordion-item-header -->
                    <div id="collapse1" class="collapse" data-parent="#accordion">
                    <div class="accordion-item__body">
                        <p>With any financial product that you buy, it is important that you know you are getting the best
                        advice from a reputable company as often</p>
                    </div><!-- /.accordion-item-body -->
                    </div>
                </div><!-- /.accordion-item -->
                <div class="accordion-item">
                    <div class="accordion-item__header" data-toggle="collapse" data-target="#collapse2">
                    <a class="accordion-item__title" href="#">Do I have to commit to a contract?</a>
                    </div><!-- /.accordion-item-header -->
                    <div id="collapse2" class="collapse" data-parent="#accordion">
                    <div class="accordion-item__body">
                        <p>With any financial product that you buy, it is important that you know you are getting the best
                        advice from a reputable company as often</p>
                    </div><!-- /.accordion-item-body -->
                    </div>
                </div><!-- /.accordion-item -->
                <div class="accordion-item opened">
                    <div class="accordion-item__header" data-toggle="collapse" data-target="#collapse3">
                    <a class="accordion-item__title" href="#">What Payment Methods Are Available?</a>
                    </div><!-- /.accordion-item-header -->
                    <div id="collapse3" class="collapse show" data-parent="#accordion">
                    <div class="accordion-item__body">
                        <p>With any financial product that you buy, it is important that you know you are getting the best
                        advice from a reputable company as often</p>
                    </div><!-- /.accordion-item-body -->
                    </div>
                </div><!-- /.accordion-item -->
                </div><!-- /.accordion --> 
            {% endcomment %}
        </div><!-- /.col-lg-8 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
    </section><!-- /.Text Content Section -->

    <!-- =========================== 
    portfolio carousel 
    ============================= -->
    <section class="portfolio-carousel pb-60">
        <div class="container">
            <div class="row align-items-center mb-20">
            <div class="col-sm-12 col-md-12 col-lg-5">
                <h3 class="heading__title mb-20">Related Products & Services</h3>
            </div><!-- /.col-lg-6 -->
            </div><!-- /.row -->
            <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="slick-carousel" id="filter-carousel"
                data-slick='{"slidesToShow": 4, "arrows": false, "dots": true, "responsive": [ {"breakpoint": 992, "settings": {"slidesToShow": 2}}, {"breakpoint": 768, "settings": {"slidesToShow": 1}}]}'>
                {% for product in similar_products %}
                <!-- portfolio item #1 -->
                    <div class="portfolio-item Construction all">
                        <div class="portfolio-item__img">
                        <img src="{{ product.image.url }}" style='height:250px' alt="portfolio img">
                        </div><!-- /.portfolio-img -->
                        <div class="portfolio-item__hover">
                        <div class="portfolio-item__content">
                            <h4 class="portfolio-item__title"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
                            <div class="portfolio-item__cat">
                            <a href="{{ product.get_absolute_url }}">{{ product.brand }}</a><a href="{{ product.get_absolute_url }}">{{ product.type }}</a>
                            </div><!-- /.portfolio-cat -->
                        </div><!-- /.portfolio-content -->
                        </div><!-- /.portfolio-item__hover -->
                    </div><!-- /.portfolio-item -->
                {% endfor %}
                </div><!-- /.carousel -->
            </div><!-- /.col-lg-12 -->
            </div><!-- /.row -->
            <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 d-flex justify-content-end">
                <a href="{% url 'product:product_list' %}" class="btn btn__link btn__loadMore">
                <span class="mr-2">Explore All Projects</span> <i class="icon-arrow-right1"></i>
                </a>
            </div><!-- /.col-lg-12 -->
            </div>
        </div><!-- /.container -->
    </section><!-- /.portfolio carousel -->


{% endblock body %}