blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path ('', views.article_list_view, name='article_list'), 
    path ('detail/<slug>', views.ArticleDetail.as_view(), name='article_detail'),
    # path ('search/', views.search_view, name='search'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details_view, name='cart_details'),
    path('add/', views.add_product_to_cart_view, name='add_product_to_cart'),
    path('remove/', views.remove_from_cart_view, name='remove_from_cart'),
    path('clear/', views.clear_cart_view, name='clear_cart'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    # Django Admin Urls
    path('admin/', admin.site.urls),

    # # Django Tool-Bar Urls
    # path("__debug__/", include("debug_toolbar.urls")),

    # Product App Urls
    path('products/', include('product.urls', namespace='product')),

    # Blog App Urls
    path('blog/', include('blog.urls', namespace='blog')),

    # Cart App Urls
    path('cart/', include('cart.urls', namespace='cart')),

    # Pages App Urls
    path('', include('pages.urls', namespace='pages')),

    # Django Ckeditor-5 Urls
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),

]

# serve static and media files from development server
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('about-us/', views.about_us_view, name='about_us'),
    path('contact-us/', views.contact_us_view, name='contact_us'),
    path('oneweb-preorder/', views.oneweb_preorder_view, name='oneweb-preorder'),
    path('land/', views.land_view, name='land'),
    path('air/', views.air_view, name='air'),
    path('marine/', views.marine_view, name='marine'),
    path('our-planet/', views.our_planet_view, name='our_planet'),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.product_list_view, name='product_list'),
    path("detail/<slug:slug>/", views.product_detail_view, name="product_detail"),
    path("search/", views.search_view, name="search"),
    path('download-pdf/<int:product_id>/', views.download_pdf_view, name='download_pdf'),
]

templates/_base.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <meta name="description" content="Eteon - Construction And Building Template">
        <link href="{% static "product/assets/images/favicon/ATHENA2.jpg"%}" rel="icon">
        <title>{% block title %}{% endblock %} - Athena Telecom</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Barlow:400,500,600,700%7cHeebo:400,500,700&display=swap">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css">
        <link rel="stylesheet" href="{% static "product/assets/css/libraries.css"%}">
        <link rel="stylesheet" href="{% static "product/assets/css/style.css"%}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        {% block front_css %}
        {% endblock %}
    </head>
    <body>
        
        {% block header %}
        
        {% include "header2.html" %}

        {% endblock header %}

        {% block body %}
        
        {% endblock %}

        {% include "footer.html" %}

        
        <script src="{% static "product/assets/js/jquery-3.5.1.min.js"%}"></script>
        <script src="{% static "product/assets/js/plugins.js"%}"></script>
        <script src="{% static "product/assets/js/main.js"%}"></script>
        {% block front_js %}
        
        {% endblock front_js %}
    </body>
</html>

templates/footer.html
{% load static %}

<!-- ========================
    Footer
========================== -->
<footer class="footer">
    {% comment %} <div class="footer-contact">
        <div class="container">
            <div class="row">
                <div class="offset-lg-4 col-sm-12 col-md-12 col-lg-8 d-flex flex-wrap justify-content-between">
                <div class="footer-contact__item d-flex align-items-center">
                    <div class="footer-contact__icon">
                    <i class="icon-phone1"></i>
                    </div><!-- /.footer-contact__icon -->
                    <div class="footer-contact__text">
                    <span>Call Us:</span>
                    <strong><a href="tel:00123968574">(002) 123968574</a></strong>
                    </div><!-- /.footer-contact__text -->
                </div><!-- /.footer-contact__item -->
                <div class="footer-contact__item d-flex align-items-center">
                    <div class="footer-contact__icon">
                    <i class="icon-envelope1"></i>
                    </div><!-- /.footer-contact__icon -->
                    <div class="footer-contact__text">
                    <span>Email Us:</span>
                    <strong><a href="mailto:Eteon@7oroof.com">Eteon@7oroof.com</a></strong>
                    </div><!-- /.footer-contact__text -->
                </div><!-- /.footer-contact__item -->
                <div class="footer-contact__item d-flex align-items-center">
                    <div class="footer-contact__icon">
                    <i class="icon-clock1"></i>
                    </div><!-- /.footer-contact__icon -->
                    <div class="footer-contact__text">
                    <span>Opening Hours:</span>
                    <strong>Mon-Fri: 8am – 7pm</strong>
                    </div><!-- /.footer-contact__text -->
                </div><!-- /.footer-contact__item -->
                </div><!-- /.col-lg-8 -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.footer-contact --> {% endcomment %}
    <div class="footer-primary bg-primary">
        <div class="container">
        <div class="row">
            {% comment %} <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 footer-widget footer-widget__newsletter">
            <form class="footer-widget__newsletter__form">
                <i class="footer-widget__newsletter__icon icon-brush"></i>
                <h6 class="footer-widget__newsletter__title">Sign Up For Industry Alerts, News & insights</h6>
                <div class="form-group mb-0">
                <input type="text" class="form-control" placeholder="Your Email Address">
                <button type="submit" class="btn btn__primary">Subscribe</button>
                </div>
            </form>
            </div><!-- /.col-xl-4 -->
            {% endcomment %}
            <div class="col-sm-6 col-md-6 col-lg-3 col-xl-3 footer-widget">
            <h6 class="footer-widget__title">Eteon Constructions</h6>
            <div class="footer-widget-body">
                <p class="mb-20">A leading developer of A-grade commercial, industrial and residential projects in USA.
                Since its foundation the company has doubled its turnover year on year with its staff.</p>
                <a href="{% url 'pages:contact_us' %}" class="btn btn__primary btn__link btn__icon">
                <i class="icon-arrow-right1"></i><span>Request A Quote</span>
                </a>
            </div><!-- /.footer-widget-body -->
            </div><!-- /.col-xl-2 --> 
            <div class="col-sm-6 col-md-6 col-lg-2 col-xl-2 footer-widget footer-widget-nav">
            <h6 class="footer-widget__title">Links</h6>
            <div class="footer-widget-body">
                <nav>
                <ul class="list-unstyled">
                    <li><a href="{% url 'pages:about_us' %}">About Us</a></li>
                    {% comment %} <li><a href="leadership-team.html">Meet Our Team</a></li> {% endcomment %}
                    <li><a href="{% url 'blog:article_list' %}">News & Articles</a></li>
                    <li><a href="{% url 'product:product_list' %}">Our Products</a></li>
                    {% comment %} <li><a href="careers.html">Careers</a></li> {% endcomment %}
                </ul>
                </nav>
            </div><!-- /.footer-widget-body -->
            </div><!-- /.col-xl-2 -->
            <div class="col-sm-12 col-md-6 col-lg-3 col-xl-3 footer-widget">
            <h6 class="footer-widget__title">Quick Contact</h6>
            <div class="footer-widget-body">
                <p>Office 3315, Churchill Executive Tower, Business Bay, Dubai-UAE.</p>
                <p>If you have any questions or need help, feel free to contact with our team.</p>
                <p class="footer-contact__phone d-flex align-items-center">
                <i class="icon-phone1"></i>
                <i><a href="tel:+97145541775">+97145541775</a></i>
                <i><a href="tel:+971508792341">+971508792341</a></i>
                <a href="tel:+18154564747">+18154564747</a>
                </p>
            </div><!-- /.footer-widget-body -->
            </div><!-- /.col-xl-4 -->
        </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.footer-primary -->
    <div class="footer-secondary">
        <div class="container">
        <div class="row align-items-center">
            <div class="col-sm-12 col-md-12 col-lg-8 d-flex flex-wrap align-items-center">
            <img src="{% static "product/assets/images/favicon/footer.jpg"%}" style="max-width:190px;" alt="logo" class="mr-20">
            <nav>
                {% comment %} 
                    <ul class="footer__copyright-links list-unstyled d-flex flex-wrap mb-0">
                    <li><a href="#">Terms & Conditions </a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Sitemap</a></li>
                    <li><a href="#">Employee login</a></li>
                    </ul> 
                {% endcomment %}
                <p class="mb-0"> Copyright, 2023 Athena Telecommunications LLC. All right reserved.
                </p>
            </nav>
            </div><!-- /.col-lg-8 -->
            <div class="col-sm-12 col-md-12 col-lg-4">
            <ul class="social__icons list-unstyled justify-content-end mb-0">
                <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
            </ul><!-- /.social-icons -->
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.footer-secondary -->
</footer><!-- /.Footer -->
<button id="scrollTopBtn"><i class="fas fa-long-arrow-alt-up"></i></button>

templates/header2.html
{% load static %}

    <!-- =========================
        Header
    =========================== -->
    <header class="header header-transparent header-layout3">
        <nav class="navbar navbar-expand-lg sticky-navbar">
            <div class="container">
            <a class="navbar-brand" style='line-height:60px;' href="{% url 'pages:home' %}">
                <img src="{% static "product/assets/images/logo/logo-light.jpg"%}" class="logo-light" alt="logo">
                <img src="{% static "product/assets/images/logo/logo-dark.jpg"%}" class="logo-dark" alt="logo">
            </a>
            <button class="navbar-toggler" type="button">
                <span class="menu-lines"><span></span></span>
            </button>
            <div class="collapse navbar-collapse" id="mainNavigation">
                <ul class="navbar-nav mx-auto">
                <li class="nav__item with-dropdown">
                    <a href="{% url 'pages:home' %}" class="nav__item-link">Home</a>
                </li><!-- /.nav-item -->
                <li class="nav__item with-dropdown">
                    <a href="{% url 'product:product_list' %}" class="nav__item-link">Services & Products</a>
                </li><!-- /.nav-item -->
                <li class="nav__item with-dropdown">
                    <a href="{% url 'blog:article_list' %}" class=" nav__item-link">Blog</a>
                </li><!-- /.nav-item -->
                <li class="nav__item with-dropdown">
                    <a href="{% url 'pages:oneweb-preorder' %}" class=" nav__item-link">OneWeb Pre-Order</a>
                </li><!-- /.nav-item -->
                <li class="nav__item with-dropdown">
                    <a href="{% url 'pages:about_us' %}" class="nav__item-link">About Us</a>
                </li><!-- /.nav-item -->
                <li class="nav__item">
                    <a href="{% url 'pages:contact_us' %}" class="nav__item-link">Contact Us</a>
                </li><!-- /.nav-item -->
                </ul><!-- /.navbar-nav -->
            </div><!-- /.navbar-collapse -->
            <ul class="header-actions__list list-unstyled d-flex align-items-center mb-0">
                <li>
                <a href="{% url 'cart:cart_details' %}" class="btn btn__white header__btn__sm">Cart {{ cart|length }} Items</a>
                </li>
            </ul><!-- /.actions__list -->
            </div><!-- /.container -->
        </nav><!-- /.navabr -->
    </header><!-- /.Header -->